package com.ssnagin.collectionmanager;
/*
 * This source file was generated by the Gradle 'init' task
 */

import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Entry script for running Application
 * @author developer
 */
@EqualsAndHashCode
@ToString
public class App {
    public static void main(String[] args) {

    }
}
