/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ssnagin.lab5java.sem2.lab5;

import com.ssnagin.lab5java.sem2.lab5.collection.CollectionManager;
import com.ssnagin.lab5java.sem2.lab5.collection.model.Album;
import com.ssnagin.lab5java.sem2.lab5.collection.model.Coordinates;
import com.ssnagin.lab5java.sem2.lab5.collection.model.MusicBand;
import com.ssnagin.lab5java.sem2.lab5.collection.model.MusicGenre;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.Arrays;

/**
 * Entry script for running Application
 * @author developer
 */
@EqualsAndHashCode
@ToString
public class App {
    public static void main(String[] args) {
        Core.getInstance().start(args);
    }
}
