package com.ssnagin.collectionmanager;/*
 * This source file was generated by the Gradle 'init' task
 */

import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.io.OutputStream;
import java.io.PrintStream;

/**
 * Entry script for running Application
 *
 * @author developer
 */
@EqualsAndHashCode
@ToString
public class Client {

    private static class NullOutputStream extends OutputStream {
        @Override public void write(int b) { }
    }

    public static void main(String[] args) {

        System.setErr(new PrintStream(new NullOutputStream())); // убрать в релизе

        Core core = Core.getInstance();
        core.setArgs(args);
        core.start();
    }
}